"""
THE HARD CORE.  (Ben-owned. Students do not edit this file.)

Everything hard to reason about lives here and NOWHERE else:
  * concurrent fan-out of electronic-structure evaluations
  * a persistent, content-addressed memo cache keyed by ESRequest
  * backpressure (a cap on max-in-flight jobs)
  * priority (reference-state work before speculative spawn-geometry work)
  * crash recovery via deterministic replay: on restart, requests whose
    results are already on disk return instantly (cache HIT); only work that
    never finished is actually dispatched.

The physics tier calls exactly one method -- `evaluate(requests)` -- which
LOOKS synchronous and blocks until every result is ready. Underneath it is the
inverted, concurrent, resilient machinery. That inversion is sealed behind this
one call, which is the whole architectural bet: the inversion sinks to the
floor, and the physics above reads as a straight-line narrative.

Two interchangeable backends implement the SAME `evaluate` contract:
  * ThreadedExecutor  -- concurrency via a thread pool (works out of the box)
  * ParslExecutor     -- concurrency + HPC scheduling + durable app-caching
                         rented from Parsl (drop-in; see class docstring)
Swapping one for the other changes NOTHING in the physics tier.
"""
from __future__ import annotations

import concurrent.futures as cf
import hashlib
import pickle
import threading
from pathlib import Path

from .es_provider import ESRequest, ESResult, ElectronicStructureBackend


def _key(req: ESRequest) -> str:
    """Content-addressed cache key. Same request -> same file -> computed once,
    ever, across the original run and every replay after every crash."""
    h = hashlib.sha256(pickle.dumps(req)).hexdigest()
    return h[:32]


class _DiskCache:
    """The persistent memo. This is what makes replay cheap and is the entire
    resilience mechanism for a pure-Pattern-A run: physics re-executes from the
    last checkpoint, and every ES call it repeats is served from here rather
    than recomputed."""
    def __init__(self, root: str):
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def get(self, req: ESRequest):
        f = self.root / f"{_key(req)}.pkl"
        if f.exists():
            with open(f, "rb") as fh:
                return pickle.load(fh)
        return None

    def put(self, req: ESRequest, result: ESResult) -> None:
        f = self.root / f"{_key(req)}.pkl"
        tmp = f.with_suffix(".tmp")
        with open(tmp, "wb") as fh:            # atomic: write-then-rename so a
            pickle.dump(result, fh)            # crash mid-write can't corrupt
        tmp.replace(f)                         # the cache


class ThreadedExecutor:
    """Concurrent, cached, backpressured executor over a thread pool.

    `evaluate` blocks until all requested results exist, servicing only
    cache-misses concurrently. From the physics tier this is a plain function
    that takes a list and returns a dict -- no future, no callback, no await.
    """
    def __init__(self, backend: ElectronicStructureBackend,
                 cache_dir: str, max_in_flight: int = 8):
        self.backend = backend
        self.cache = _DiskCache(cache_dir)
        self._sem = threading.Semaphore(max_in_flight)   # backpressure
        self._pool = cf.ThreadPoolExecutor(max_workers=max_in_flight)

    def _run_one(self, req: ESRequest) -> ESResult:
        with self._sem:                        # cap max-in-flight
            res = self.backend.compute_one(req)
        self.cache.put(req, res)               # persist immediately on success
        return res

    def evaluate(self, requests, priority=None) -> dict[ESRequest, ESResult]:
        """Return {request: result} for every request. Blocks until done.

        `priority(req) -> int` (lower first) lets the driver push reference-
        state gradients ahead of speculative spawn-geometry energies. It does
        not change results, only dispatch order -- so it never affects replay.
        """
        out, misses = {}, []
        seen = set()
        for req in requests:
            if req in seen:                    # identical requests (e.g. a spawned
                continue                       # child sharing its parent geometry)
            seen.add(req)                      # are the SAME computation -- run once
            hit = self.cache.get(req)          # replay absorbs completed work
            if hit is not None:
                out[req] = hit
            else:
                misses.append(req)
        if priority is not None:
            misses.sort(key=priority)
        futs = {self._pool.submit(self._run_one, r): r for r in misses}
        for fut in cf.as_completed(futs):      # completion order is arbitrary...
            req = futs[fut]
            out[req] = fut.result()            # ...so we key by request, never
        return out                             # rely on order. Replay-safe.

    def shutdown(self):
        self._pool.shutdown(wait=True)


class ParslExecutor:
    """Drop-in replacement that rents the resilient tier from Parsl.

    Parsl gives, off the shelf, exactly the pieces this file otherwise
    hand-rolls: a futures-based DAG executor, HPC backends (Slurm/etc.), retry
    policy, and -- critically -- app caching + checkpointing that persists
    memoized results keyed by app inputs and reuses them across runs. That IS
    the persistent memo cache above, maintained by someone else.

    Sketch (kept as a docstring so the skeleton runs without Parsl installed):

        import parsl
        from parsl import python_app
        from parsl.config import Config
        # ... configure an HTEX executor with a Slurm provider, app_cache=True,
        #     checkpoint_mode='task_exit' ...

        @python_app(cache=True)
        def _es_app(req, backend):
            return backend.compute_one(req)

        def evaluate(self, requests, priority=None):
            futs = {r: _es_app(r, self.backend) for r in requests}  # cache hits
            return {r: f.result() for r, f in futs.items()}         # are instant

    The physics tier is byte-for-byte identical whether this or ThreadedExecutor
    is wired in. That interchangeability is the proof the seam is in the right
    place.
    """
    pass
